name = "ohhelp2"
version = "2.3.0"
license = "LicenseRef-OhHelp-NonCommercial AND MIT"
author = "Hiroshi Nakashima and contributors"
maintainer = "Jin Nakazono <nakazono.jin@port.kobe-u.ac.jp>"
copyright = "Copyright (C) 2009-2015 Hiroshi Nakashima; Copyright (C) 2023 Jin Nakazono"

[build]
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
