/* File: oh_mode.h
   Public transbound currmode constants.
*/
#ifndef OH_MODE_H
#define OH_MODE_H

enum {
  OH_MODE_NORMAL_PRIMARY = 0,
  OH_MODE_NORMAL_SECONDARY = 1,
  OH_MODE_REBALANCE_SECONDARY = -1,
  OH_MODE_ANY_PRIMARY = 2,
  OH_MODE_ANY_SECONDARY = 3
};

#define OH_MODE_NORM_PRI OH_MODE_NORMAL_PRIMARY
#define OH_MODE_NORM_SEC OH_MODE_NORMAL_SECONDARY
#define OH_MODE_REB_SEC  OH_MODE_REBALANCE_SECONDARY
#define OH_MODE_ANY_PRI  OH_MODE_ANY_PRIMARY
#define OH_MODE_ANY_SEC  OH_MODE_ANY_SECONDARY

#endif
